format_version: 10
pipelines:
  tools-tf-apply:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3a51435:
        git: https://github.com/saiyadaz/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - APPLY:
          fetch_materials: true
          approval:
            type: manual
          allow_only_on_success: false
          jobs:
           terraform-apply:
              tasks:
                - exec: { command: terraform, arguments: [ "init"], run_if: passed }
                - exec: { command: terraform, arguments: [ "apply", "-auto-approve"], run_if: passed }
