- name: Install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    executable: pip3.11

- name: Create Job xml file
  ansible.builtin.template:
    src: jobs/mbranch.xml
    dest: /tmp/{{item}}.xml
  loop:
    - frontend
    - cart
    - catalogue
    - user
    - shipping
    - payment
    - dispatch
  delegate_to: localhost
  become: false

- name: Create Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: "roboshop-{{item}}"
    password: "{{secrets.jenkins_password}}"
    url: http://jenkins-internal.devopssz14.online:8080
    user: "{{secrets.jenkins_user}}"
  loop:
    - frontend
    - cart
    - catalogue
    - user
    - shipping
    - payment
    - dispatch

