- name: Install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    executable: pip3.9

- name: Create Job xml file
  ansible.builtin.template:
    src: jobs/mbranch.xml
    dest: /tmp/{{item}}.xml
  loop:
    - frontend
    - backend
  delegate_to: localhost


- name: Create Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: "{{item}}"
    password: "admin123"
    url: http://jenkins.devopssz14.online:8080
    user: "admin"
  loop:
    - frontend
    - backend

