- name: Jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins_setup.yml
  when: jenkins_setup | bool

- name: Jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins_jobs.yml
  when: jenkins_jobs | bool






