- name: Install vault Yum Repo file
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Start vault Service
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: true

